### ISSUE TITLE
Install error in version 4.20.0

### ISSUE THREAD

**Issue by muhammedogz** [AgoraIO/agora-rtc-web#4]
### AgoraRTC SDK version

4.20.0

### Fail Rate

1

### Link to minimal reproduction

Any repo with "npm i agora-rtc-sdk-ng"

### Steps to reproduce

Just run `npm i agora-rtc-sdk-ng`

### What is expected?

Working installation 

### What is actually happening?

Not working :)

**Comment by muhammedogz** [comment]
It seems last version of `agora-rte-extension` is "1.2.3" but in some places, this package trying to get the wrong version as "1.2.4".

While waiting for a fix, I will be doing override in my package json like this.

```js
  "overrides": {
    "agora-rte-extension": "1.2.3"
  }
```

**Comment by rahulnainwalttn** [comment]
@agora-js/media is trying to install agora-rte-extension "1.2.4".

**Comment by rahulkarasiTtn** [comment]
facing same issue

**Comment by rohansingh-ttn** [comment]
> @agora-js/media is trying to install agora-rte-extension "1.2.4". Facing same issue due to it.

Yes @rahulnainwalttn, you are right!

Facing a similar issue with the dependencies. The `"agora-rtc-sdk-ng"` version is set to `"4.19.3"`, and it has a dependency on `@agora-js/media`, which, in turn, relies on `agora-rte-extension: 1.2.4`. This results in a version mismatch issue.

**Comment by rohansingh-ttn** [comment]
> It seems last version of `agora-rte-extension` is "1.2.3" but in some places, this package trying to get the wrong version as "1.2.4".
> 
> While waiting for a fix, I will be doing override in my package json like this.
> 
> ```js
>   "overrides": {
>     "agora-rte-extension": "1.2.3"
>   }
> ```

![i-am-stuck](https://github.com/AgoraIO/agora-rtc-web/assets/137080481/fe69bdfa-e5b6-4a68-929e-b91e7607a6c9)

Thanks, @muhammedogz, it's working now.

**Comment by simo-an** [comment]
agora-rte-extension "1.2.4" has been published!
